In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Car Dataset Processed.csv')

In [3]:
df.head() # y column is price 
# for text data enconding used, two colunms manufacturing_year and registration_year = feature selction , problem multicolineararity

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [4]:
#torque(Nm)

In [5]:
# preprocessing , 4 category 
df['insurance_validity'].value_counts()

Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: insurance_validity, dtype: int64

In [6]:
d1 = {'Comprehensive':0,'Third Party insurance':1,
                              'Zero Dep':2,'Not Available':3,'Third Party':1}
df['insurance_validity']=df['insurance_validity'].map(d1)

In [7]:
df['insurance_validity'].value_counts()

0    1081
1     352
2      64
3       2
Name: insurance_validity, dtype: int64

In [8]:
# 2
df['fuel_type'].value_counts()

Petrol    997
Diesel    480
CNG        22
Name: fuel_type, dtype: int64

In [9]:
d2 = {'Petrol':0,'Diesel':1,'CNG':2}
df['fuel_type']=df['fuel_type'].map(d2)

In [10]:
df['fuel_type'].value_counts()

0    997
1    480
2     22
Name: fuel_type, dtype: int64

In [11]:
# 3
df['ownsership'].value_counts()

First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: ownsership, dtype: int64

In [12]:
d4 = {'First Owner':1,'Second Owner':2,'Third Owner':3,'Fifth Owner':5,'Fourth Owner':4}
df['ownsership']=df['ownsership'].map(d4)

In [13]:
df['ownsership'].value_counts()

1    1236
2     240
3      21
5       2
Name: ownsership, dtype: int64

In [14]:
# 4
df['transmission'].value_counts()

Manual       832
Automatic    667
Name: transmission, dtype: int64

In [15]:
d3= {'Manual':0,'Automatic':1}
df['transmission']=df['transmission'].map(d3)

In [16]:
df['transmission'].value_counts()

0    832
1    667
Name: transmission, dtype: int64

In [17]:
df['registration_year'].value_counts()

Jul-18    38
Jul-17    29
Aug-18    29
May-17    26
Oct-18    25
          ..
Feb-13     1
Nov-09     1
Apr-13     1
Nov-11     1
Sep-12     1
Name: registration_year, Length: 175, dtype: int64

In [18]:
df['registration_year'] = df['registration_year'].astype(str).str[-2:].astype(int)
df['registration_year']

0       17
1       21
2       18
3       19
4       19
        ..
1494    22
1495    20
1496    17
1497    18
1498    18
Name: registration_year, Length: 1499, dtype: int32

In [19]:
X = df[['insurance_validity','fuel_type','kms_driven','ownsership','transmission','registration_year']]
y = df['price(in lakhs)']

In [20]:
X.head()

,insurance_validity,fuel_type,kms_driven,ownsership,transmission,registration_year
0,0,0,56000,1,1,17
1,0,0,30615,1,1,21
2,0,1,24000,1,1,18
3,0,0,18378,1,0,19
4,0,0,44900,1,1,19

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [21]:
from sklearn.linear_model import LinearRegression 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [23]:
models={'LinReg':LinearRegression()
        ,'KNN-5':KNeighborsRegressor(n_neighbors=5),
        'SVM-Poly':SVR(kernel='poly')} 
# R2 Score ecould be negative and model is worse
for name, model in models.items():
    model.fit(X_scaled, y)
    sc = model.score(X_scaled, y)
    print(name, sc)

LinReg 0.02412956601154448
KNN-5 0.1372261352315166
SVM-Poly -0.0022666528426777965

In [24]:
final_model=models['KNN-5']

In [25]:
# input function always in string 
insurance_validity= input('insurance_validity:')
fuel_type= input('fuel_type:')
kms_driven= input('kms_driven:')
ownsership= input('ownsership:')
transmission= input('transmission:')
registration_year = input('registration_year:')

insurance_validity = d1[insurance_validity]
fuel_type = d2[fuel_type]
transmission = d3[transmission]
ownsership = d4[ownsership]
kms_driven =int(kms_driven)
registration_year = int(str(registration_year)[-2:])


test = [[insurance_validity, fuel_type, kms_driven, ownsership, transmission, registration_year]]
test_scaled = scaler.transform(test)
yp = final_model.predict(test_scaled)[0]
print(f'Predicted Price: {yp:.2f} lakhs')
print(f'Predicted Price in ₹: {yp*100000:.0f}')

insurance_validity:Comprehensive
fuel_type:Petrol
kms_driven:1000
ownsership:First Owner
transmission:Automatic
registration_year:20
Predicted Price: 25.56 lakhs
Predicted Price in ₹: 2556000

C:\Users\Aishwarya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [28]:
import pickle
pickle.dump(final_model,open('final_model.pkl','wb'))
pickle.dump(scaler, open('scaler.pkl','wb'))